name: Slack Pull Request Open Notification

on:
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: jpcrespi/slack-pr-open-notification-action@master
      env: 
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        PULL_REQUEST: ${{ toJson(github.event.pull_request) }}
        GITHUB_SLACK_IDS: githubuser1=SLACKUSERID1,githubuser2=SLACKUSERID2
        SEND_GROUP_ID_MENTIONS: GROUPIDDDD,GGGGROUPID
        IS_SEND_HERE_MENTION: false
        IS_PR_FROM_FORK: false
        MAKE_PRETTY : false
        MAKE_COMPACT : true